#+TITLE: Exercícios do Capítulo 15
#+AUTHOR: Lourenço Henrique Moinheiro Martins Sborz Bogo - 11208005
#+LANGUAGE: pt-br

#+LATEX_HEADER: \usepackage[hyperref, x11names]{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks = true, urlcolor = SteelBlue4, linkcolor = black}
#+LATEX_HEADER: \usepackage[AUTO]{babel}

\newpage

* Exercício 3
  \paragraph{}Precisamos deduzir a fórmula do erro da /Midpoint Rule/.
  Para isso, primeiro vamos expandir a função $f(x)$, que
  queremos, integrar usando taylor, até o termo de segunda ordem, 
  ao redor do ponto $\frac{a+b}{2}$ (a e b são nossas bordas de
  integração):

  $f(x) = f(\frac{a+b}{2}) + (x-\frac{a+b}{2})f'(\frac{a+b}{2}) + (x-\frac{a+b}{2})^2\frac{f''(\xi_x)}{2}$ \\
  
  Agora, iremos calcular o erro em si:

  \noindent$\displaystyle\int_a^b f(x)dx - \displaystyle\int_a^b f(\frac{a+b}{2})dx = \\
  = \displaystyle\int_a^b f(\frac{a+b}{2}) + (x-\frac{a+b}{2})f'(\frac{a+b}{2}) + (x-\frac{a+b}{2})^2\frac{f''(\xi_x)}{2} - f(\frac{a+b}{2}) = \\
  = \displaystyle\int_a^b(x-(\frac{a+b}{2}))f'(\frac{a+b}{2}) + \frac{(x-\frac{a+b}{2})^2}{2}f''(\xi_x)dx = \\
  = \displaystyle\int_a^b(x-(\frac{a+b}{2}))f'(\frac{a+b}{2}) + \displaystyle\int_a^b\frac{(x-\frac{a+b}{2})^2}{2}f''(\xi_x)dx = \\
  = 0 + \frac{f''(\eta)}{2}\displaystyle\int_a^b(x-\frac{a+b}{2})^2dx$  (Pelo T.V.M. para integrais) $= \\ 
  = \frac{(b-a)^3}{24}f''(\eta)$, $\eta \in [a, b]$.
  
\newpage

* Exercício 4
** (a)
   Sabemos que o erro da /Hermite Cubic Interpolation/ é:\\
  
   $\displaystyle\frac{f^4(\eta)(x-a)^2(x-b)^2}{4!}$ \\

   \noindent Portanto podemos escrever:\\

   $\displaystyle f(x) - p(x) = \frac{f^4(\eta)(x-a)^2(x-b)^2}{4!}$ \\

   \noindent Depois, integramos os dois lados de a até b, conseguindo:\\

   $\displaystyle\int_a^b f(x) - p(x) 
   = \displaystyle\int_a^b \frac{f^4(\eta)(x-a)^2(x-b)^2}{4!} \rightarrow \\
   \rightarrow \displaystyle\int_a^b f(x) - \int_a^b p(x) =
   \frac{f^4(\eta)}{4!}\int_a^b(x-a)^2(x-b)^2$ \\
   
   \noindent Ou seja, o erro de usarmos esse método para calcular a integral é \\ 
   $\displaystyle\frac{f^4(\eta)}{4!}\displaystyle\int_a^b(x-a)^2(x-b)^2$.\\
   
   \noindent Agora precisamos simplificar essa expressão:\\
   
   $\displaystyle\frac{f^4(\eta)}{4!}\displaystyle\int_a^b(x-a)^2(x-b)^2 = 
   \frac{f^4(\eta)}{4!}\displaystyle\int_a^b(x^2-2ax+a^2)(x^2-2bx+b^2) = \\
   = \frac{f^4(\eta)}{4!}\frac{6b^5-6a^5+10b^5+40ab^4+10a^2b^3-10a^5-10a^3b^2-40a^4b+15a^2+45a^4b-15b^5-45ab^4}{30} = \\
   = \frac{f^4(\eta)(b-a)^5}{720}$, $\eta \in [a, b]$.
  
   \newpage

** (b)
   
   #+INCLUDE: "ex4cap15.py" :src py :lines "3-"

   |-----------+--------------------+------------------+---------------------+--------------------|
   | Intervalo | Trapezoid          | Simpson          | Midpoint            | Corrected          |
   |-----------+--------------------+------------------+---------------------+--------------------|
   |-----------+--------------------+------------------+---------------------+--------------------|
   | [0, 1]    | 0.1408             | $6\cdot 10^{-4}$ | $6.96\cdot 10^{-2}$ | $2\cdot 10^{-3}$   |
   |-----------+--------------------+------------------+---------------------+--------------------|
   | [0.9, 1]  | $2.2\cdot 10^{-4}$ | $9\cdot 10^{-9}$ | $1.1\cdot 10^{-4}$  | $3.6\cdot 10^{-8}$ |
   |-----------+--------------------+------------------+---------------------+--------------------|
   |-----------+--------------------+------------------+---------------------+--------------------|

   Podemos perceber que Corrigido aproximou melhor que a maioria dos outros métodos, com exceção do de Simpson,
   o que já era esperado, já que ele usa um polinômio de segundo grau, ao invés de um polinômio de primeiro.

   \newpage

* Exercício 6
** (a)
   Para conseguir a fórmula é muito simples. Ao invés de aplicar a fórmula direto
   em $[a, b]$, vamos quebrar o intervalo em vários intervalos menores, equidistantes,
   e aplicar a fórmula nesses intervalos.
   Começaremos com a notação:
   
   - $h = (a-b)/n$, com $n$ sendo o número de sub-intervalos.
   - $x_i = a + ih$

   Temos então que a fórmula seria construída aplicando a fórmula do trapezío corrigida
   para os intervalos $[x_{i}, x_{i+1}]$: \\

   $\displaystyle I_{cctr} = \sum_{i=0}^{n-1}(\frac{x_{i+1}-x_i}{2}(f(x_{i+1})+f(x_i))+\frac{(x_{i+1}-x_i)^2}{12}(f'(x_{i+1})-f'(x_i))) = \\
   = \sum_{i=0}^{n-1}(\frac{h}{2}(f(x_{i+1})+f(x_i))+\frac{h^2}{12}(f'(x_{i+1})-f'(x_i))) = \\
   = \frac{h}{2}\sum_{i=0}^{n-1}(f(x_{i+1})+f(x_i)) + \frac{h^2}{12}\sum_{i=0}^{n-1}(f'(x_{i+1})-f'(x_i))$
   
   Agora, podemos perceber que a primeira parcela dessa soma: \\ 
   $\displaystyle\frac{h}{2}\sum_{i=0}^{n-1}(f(x_{i+1})+f(x_i))$,
   é a regra do trapézio composto, e, que a segunda parcela vai se cancelar quase que inteira, sobrando apenas 
   $f'(x_0)$ e $f'(x_n)$, que são $f'(a)$ e $f'(b)$. 

   Fazendo, então, todas as simplificações necessárias, chegamos na seguinte fórmula: \\
   
   $\displaystyle h(\frac{f(a)+f(b)}{2}+\sum_{i=1}^{n-1}f(x_i)) + h^2\frac{f'(a)-f'(b)}{12} = I_{tr} + h^2\frac{f'(a)-f'(b)}{12}$

   \newpage

   Código: 
   #+INCLUDE: "ex6cap15.py" :src python :lines "3-"

   | Valor Dado no Enunciado | Não corrigida |   Corrigida |
   |-------------------------+---------------+-------------|
   |             0.746824133 |   0.746210796 | 0.746823928 |
   |                         |               |             |

   Podemos perceber que o erro na versão não corrigida é da ordem de $10^{-4} = h^4$ e
   na versão corrigida é da ordem de $10^{-6} = h^6$, ou seja, uma melhora da ordem de $10^{-2} = h^2$ nos experimentos.
   \newpage
** (b)
   Primeiro, vamos mostrar que o erro do trapézio corrigido composto 
   é $O(h^4)$:
   
   $\displaystyle I-I_{tcc} = \sum_{i=0}^{n-1}\frac{f^4(\eta_i)h^5}{720} = 
   \frac{h^5}{720}\sum_{i=0}^{n-1}f^4(\eta_i)$.

   Agora vamos multiplicar a expressão por $\frac{a-b}{nh}$. Podemos fazer
   isso pois essa fração é igual a 1.

   $\displaystyle\frac{a-b}{nh}\frac{h^5}{720}\sum_{i=0}^{n-1}f^4(\eta_i)$.

   Agora usando o Teorema do Valor Intermediário, 
   $\displaystyle \frac{\sum_{i=0}^{n-1}f^4(\eta_i)}{n} = f^4(\eta)$, $\eta \in [a, b]$, onde $[a, b]$ é o nosso intervalo de integração.\\
   
   Simplificando, temos: 

   $\displaystyle I-I_{tcc} = \frac{h^4(a-b)f^4(\eta)}{720} = O(h^4)$.\\

   Com essa informação, podemos provar o que o exercício pede:
   
   $I-I_{tcc} = O(h^4) \rightarrow I-I_{tc}-h^2\frac{f'(a)-f'(b)}{12} = O(h^4) \rightarrow \\
   \rightarrow I-I_{tc} = h^2\frac{f'(a)-f'(b)}{12}+O(h^4)$.
